---
- name: "upgrading packages."
  become: true
  apt:
    upgrade: "yes"

- name: "installing dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copying backend file"
  become: true
  copy:
    src: /root/project/backend
    dest: /root
    force: no

- name: "installing npm packages"
  become: true
  command: npm install
  args:
    chdir: /root/backend

- name: "compiling npm packages"
  become: true
  command: npm run build
  args:
    chdir: /root/backend

- name: "starting server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /root/backend/dist