---
  - name: "show remote environment"
    shell: env

  - name: "upgrading packages."
    become: true
    apt:
      upgrade: "yes"

  - name: "installing dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      update_cache: yes

  - name: "installing pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: "copy backend binaries"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "copy node_modules"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/uda_app/dist

# - name: "copying backend file"
#   become: true
#   copy:
#     src: /root/project/backend
#     dest: /root
#     force: no

# - name: "installing npm packages"
#   become: true
#   command: npm install
#   args:
#     chdir: /root/backend

# - name: "compiling npm packages"
#   become: true
#   command: npm run build
#   args:
#     chdir: /root/backend

# - name: "starting server"
#   become: true
#   command: pm2 start npm -- run start
#   args:
#     chdir: /root/backend/dist

