version : 2.1

orbs:
  slack: circleci/slack@4.1

jobs:
  build-frontend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [frontend_build]

      - run :
          name: Build frontend
          command : |
            cd frontend
            npm install
            npm run build

      - save_cache :
          paths : [frontend/node-modules]
          key   : frontend_build

      - slack/notify:
          event: fail
          template: basic_fail_1


  build-backend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [backend_build]

      - run :
          name: Build backend
          command : |
            cd backend
            npm install
            npm run build

      - save_cache :
          paths : [backend/node-modules]
          key  : backend_build

      - slack/notify:
          event: fail
          template: basic_fail_1

  test-frontend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [frontend_build]
      - run :
          name: Testing frontend
          command : |
            cd frontend
            npm install
            npm run test

  test-backend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [backend_build]
      - run :
          name: Testing Backend
          command : |
            cd backend
            npm install
            npm run test

  scan-frontend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [frontend_build]
      - run :
          name: Scanning front end.
          command : |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  scan-backend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [backend_build]
      - run :
          name: Scanning back end.
          command : |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

workflows :
  default:
    jobs:
      - build-frontend:
          context: Access_Token
      - build-backend:
          context: Access_Token
      - test-frontend :
          requires : [build-frontend]
          context: Access_Token
      - test-backend :
          requires : [build-backend]
          context: Access_Token
      - scan-frontend :
          requires : [build-frontend]
          context: Access_Token
      - scan-backend :
          requires : [build-backend]
          context: Access_Token
