version : 2.1

# Commands:
#   build-node-application :
#     description: generic run commands for node applications.
#     steps:
#       - run :
#             cd frontend
#             npm install
#             npm run build

jobs:
  build-frontend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [frontend_build]

      - run : cd frontend
      - run : npm install
      - run : npm run build

      - save_cache :
          paths : [frontend/node-modules]
          key   : frontend_build

  build-backend:
    docker :
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache :
          keys : [backend_build]

      - run : cd backend
      - run : npm install
      - run : npm run build

      - save_cache :
          paths : [backend/node-modules]
          key  : backend_build

workflows :
  default:
    jobs:
      - build-frontend
      - build-backend