version : 2.1

# Commands:
#   build-node-application :
#     description: generic run commands for node applications.
#     steps:
#       - run :
#             cd frontend
#             npm install
#             npm run build

Jobs:
  build-frontend:
    docker : circleci/node:13.8.0
    steps:
      -checkout
      - restore_cache :
          keys : [frontend_build]

      - run :
          name: Build frontend
          command :
            cd frontend
            npm install
            npm run build

      - save_cache :
        path : [frontend/node-modules]
        key  : [frontend_build]

  build-backend:
    docker : circleci/node:13.8.0
    steps:
      -checkout
      - restore_cache :
          keys : [backend_build]

      - run :
          name: Build backend
          command :
            cd backend
            npm install
            npm run build

      -save_cache :
        path : [backend/node-modules]
        key  : [backend_build]

workflows :
  default:
    jobs :
      -build-frontend
      -build-backend